//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.13 at 12:43:37 PM ALMT 
//


package org.uplifteds.xmlutil.tickets;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Tickets package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tickets_QNAME = new QName("", "Tickets");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Tickets
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TicketsType }
     * 
     */
    public TicketsType createTicketsType() {
        return new TicketsType();
    }

    /**
     * Create an instance of {@link TicketType }
     * 
     */
    public TicketType createTicketType() {
        return new TicketType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TicketsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Tickets")
    public JAXBElement<TicketsType> createTickets(TicketsType value) {
        return new JAXBElement<TicketsType>(_Tickets_QNAME, TicketsType.class, null, value);
    }

}
